### ISSUE TITLE
instant redirect not working

### ISSUE THREAD

**Issue by pietroppeter** [SciNim/nimfftw3#6]
hi! instant redirect of the docs linked page ([this](https://clonkk.github.io/nimfftw3/)) does not work for me (while the [target](https://clonkk.github.io/nimfftw3/src/htmldocs/fftw3.html) of redirection works fine).

I am not sure if it is because of my browser (Chrome 87 on Windows 10) or if it is a typo in the content attribute.

I think changing this:

```html
<meta http-equiv="refresh" content=" time ; url = src/htmldocs/fftw3.html">
```

to this (time -> 0):

```html
<meta http-equiv="refresh" content="0; url = src/htmldocs/fftw3.html">
```

should fix it (I just googled what [this meta](https://en.wikipedia.org/wiki/Meta_refresh) means, I did not know it before).

**Comment by Clonkk** [comment]
It appears you are right. I don't use Chrome so haven't noticed the problem. 
I'll fix it tonight. 
Thanks for pointing that out !

**Comment by pietroppeter** [comment]
You are welcome!
